apprdj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('produits.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

produits/urls.py
from django.urls import path
from .views import index, CreateProduct

app_name ='produits'

urlpatterns = [
    path('', index, name='index'),
    path('create-produit/', CreateProduct.as_view(), name='create_product')
]

produits/models.py
from django.db import models

class Produit(models.Model):
    nom = models.CharField(max_length=255)
    description = models.TextField()
    prix = models.FloatField()
    image = models.ImageField(upload_to='images/')
    
    def __str__(self):
        return self.nom
    
    def get_image_url(self):
        if self.image:
            return self.image.url
        return None

produits/forms.py
from django import forms

from .models import Produit

class ProduitForm(forms.ModelForm):
    prix = forms.FloatField()
    
    class Meta:
        model = Produit
        fields = [ 'nom', 'description', 'prix', 'image' ]
        
    # Valider la donnée prix
    def clean_prix(self):
        prix = self.cleaned_data.get('prix')
        
        if prix <= 0 or prix == None or prix == '':
            raise forms.ValidationError('Le prix doit être supérieur à 0.')
        
        return prix

produits/views.py
from django.shortcuts import render, HttpResponse, redirect
from django.views import View
from django.contrib import messages

from .models import Produit
from .forms import ProduitForm


def index(request, *args, **kwargs):
    liste_produits = Produit.objects.all()
    context = {
        'produits': liste_produits,
        'nom': 'Produit de la boutique'
    }
    return render(request, 'index.html', context)


# Création du formulaire manuel
# class CreateProduct(View):
#     def get(self, request, *args, **kwargs):
#         return render(request, 'produits/create_product.html')
    
#     def post(self, request, *args, **kwargs):
#         try:
#             nom = request.POST.get('nom')
#             description = request.POST.get('description')
#             prix = request.POST.get('prix')
#             image = request.FILES.get('image')
            
#             produit = Produit.objects.create(nom=nom, description=description, prix=prix, image=image)
            
#             if produit:
#                 return HttpResponse("Produit enregistré avec succès.")
#         except:
#             return HttpResponse("Erreur d'enregistrement du produit.")

# Création du formulaire avec Django
class CreateProduct(View):
    def get(self, request, *args, **kwargs):
        form = ProduitForm()

        return render(request, 'produits/create_product.html', { 'form': form })
    
    def post(self, request, *args, **kwargs):
        form = ProduitForm(request.POST, request.FILES)
        
        if form.is_valid():
            form.save()
            messages.success(request, 'Produit crée avec succès.')
            return redirect('produits:index')
        else:
            messages.error(request, "Erreur lors de l'enregistrement du produit.")
            return render(request, 'produits/create_product.html', { 'form': form })

templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Boutique Produit</title>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
      crossorigin="anonymous"
    />
  </head>
  <body>
    {% include 'navbar.html' %} {% include 'message.html' %}

    <div class="container">{% block content %} {% endblock %}</div>
  </body>
  {% include 'js.html' %}
</html>

templates/index.html
{% extends 'base.html' %} {% block content %}
<h1 class="text-center display-3">Liste des produits</h1>

<div class="row">
  {% for produit in produits %}

  <div class="col-md-4">
    <div class="card" style="width: 18rem">
      <img src="{{ produit.get_image_url }}" class="card-img-top" alt="..." />
      <div class="card-body">
        <h5 class="card-title">{{ produit.nom }}</h5>
        <h5 class="card-title">Prix : ${{ produit.prix }}</h5>
        <p class="card-text">{{ produit.description }}</p>
        <a href="#" class="btn btn-primary">Voir</a>
      </div>
    </div>
  </div>
  {% endfor %}
</div>
{% endblock %}

templates/js.html
<script
  src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
  integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
  crossorigin="anonymous"
></script>
<script
  src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
  integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r"
  crossorigin="anonymous"
></script>
<script
  src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js"
  integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy"
  crossorigin="anonymous"
></script>

templates/message.html
{% if messages %} {% for message in messages %}
<div
  class="alert alert-{{ message.tags }} alert-dismissible fade show"
  role="alert"
>
  {{ message }}
  <button
    type="button"
    class="btn-close"
    data-bs-dismiss="alert"
    aria-label="Close"
  ></button>
</div>

{% endfor %} {% endif %}

templates/navbar.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <button
      class="navbar-toggler"
      type="button"
      data-bs-toggle="collapse"
      data-bs-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'produits:create_product' %}"
            >Créer un produit</a
          >
        </li>
      </ul>
      <form class="d-flex" role="search">
        <input
          class="form-control me-2"
          type="search"
          placeholder="Search"
          aria-label="Search"
        />
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

templates/produits/create_product.html
<!DOCTYPE html>
{% extends 'base.html' %} {% block content %}
<h1 class="text-center display-3">Créer un produit</h1>
<form method="POST" enctype="multipart/form-data">
  {% csrf_token %} {{ form.as_p }}
  <button type="submit" class="btn btn-primary">Créer</button>
</form>
{% endblock %}